### ISSUE TITLE
navbar update

### ISSUE THREAD

**Issue by PadowYT2** [GIGABAIT-Official/nexus#14]
- [x] Copied poput (Release 1.6.0)
- [x] Move on hover (Release 1.6.0)
- [ ] Better navbar moved to #33

**Comment by PadowYT2** [comment]
also make connections move to right/left when cursor is it on it (idk how to spell) and make like DefaultRevamp. The `copied` should be like an alert (like cookies alert). And make it a little bigger

**Comment by Sylensky** [comment]
There is a `moveonhover-left` and a `moveonhover-right` class that makes this easily.

**Comment by PadowYT2** [comment]
doesn't seem that there is a class
![image](https://user-images.githubusercontent.com/71085027/141440088-feffe9c4-48de-4ef5-b895-e20d71930866.png

https://user-images.githubusercontent.com/71085027/141440190-4b0ed29e-88cd-4764-9f68-b5007d949dcb.mp4

)
