### ISSUE TITLE
Font doesn't change to white when enabling dark mode.

### ISSUE THREAD

**Issue by Slddev** [GIGABAIT-Official/nexus#24]
Enabling dark mode makes some text unreadable due to them being black. Worst case of this is in the navbar, where the buttons are completely invisible.

**Comment by Sylensky** [comment]
can you add some sample screenshots of the issue?

**Comment by PadowYT2** [comment]
> can you add some sample screenshots of the issue?

![image](https://user-images.githubusercontent.com/71085027/139805700-f667862b-7722-487f-8f92-84f281c76c27.png)

**Comment by PadowYT2** [comment]
i'll do it when template settings released

**Comment by PadowYT2** [comment]
ceb523bd0a741f722e2e70fe6a6b0f717a7469be
