### ISSUE TITLE
Avatar still rounded after modifying files to make it be squared.

### ISSUE THREAD

**Issue by AmnoxSA** [GIGABAIT-Official/nexus#48]
### Describe the issue

So, the default & custom avatars are rounded on namelessmc, so i've followed Sylensky's tutorial on the discord nexus support channel and they are working, but not fully. They don't get squared on everything, they don't go squared on topic and on online staff widget,

### NamelessMC Version

2.0.0-pr12

### Nexus Version

1.6.1

### To Reproduce

Go to custom/templates/Nexus, open index.tpl line 57 change from from class="ui avatar image" to class="ui mini image"
profile.tpl line 29 change from class="ui tiny circular image" to class="ui tiny image"
user_popover.tpl line 3 change from class="ui tiny circular image" to class="ui tiny image"

Forum module:
forum/view_topic.tpl line 284 change from class="ui avatar image" to class="ui mini image"

### Expected Behaviour

Every avatar would be squared now.

### Desktop

- OS: Windows 11
- Browser: Brave

### Screenshots

https://imgur.com/LosIKc3
https://imgur.com/XTFNVO9

**Comment by PadowYT2** [comment]
this is literally not a bug, u modified the template itself means it is not default, this is not nexus's fault
