### ISSUE TITLE
Crashes upon installing modules

### ISSUE THREAD

**Issue by JavaGuy12** [GIGABAIT-Official/nexus#65]
### Describe the issue

When installing the module, an exception is encountered. This is (I think) because you can't type a static declaration in PHP. The line of code in question is from /classes/NexusUtil.php.
The line which reads
`private static Language $_nexus_language` 
causes the error. Once I omitted "Language," the module installed.
`private static $_nexus_language`

### NamelessMC Version

2.0.0-pr12

### Nexus Version

1.6.1

### To Reproduce

1. Install the template by uploading.
2. Go to modules and install.

### Expected Behaviour

Nexus to install without error.

### Desktop

- OS: Windows 11
- Browser Vivaldi (Chromium fork)
- Version 5.2.2623.48

### Smartphone

n/a

**Comment by PadowYT2** [comment]
The bug is already discovered, please go to our Discord (https://resourcemc.net)
